server:
  port: 8080
  servlet:
    session:
      timeout: -1

# 多数据源配置
app:
  datasource:
    # 数据源1
    db1:
      url: jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源2
    db2:
      url: jdbc:mysql://127.0.0.1:3306/db2?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver












