boxes = [
    {
        :name => "zookeeper-leader",
        :eth1 => "192.168.3.101",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "zookeeper-follower1",
        :eth1 => "192.168.3.102",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "zookeeper-follower2",
        :eth1 => "192.168.3.103",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  
   boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["numvcpus"] = opts[:cpu]
        end

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
		  v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
		  v.customize ["modifyvm", :id, "--name", opts[:name]]
        end

        config.vm.network :public_network, ip: opts[:eth1]
      end
  end
  #Encoding.default_external = 'GBK'
  Encoding.default_external = 'UTF-8'
end